### ISSUE TITLE
System.ArgumentException: ''∞' is not a valid value for property 'To'.'

### ISSUE THREAD

**Issue by phamnamkhanhs** [belowaverage-org/SuperLauncher#23]
i run it and it show: CloseTopAnimation.To = DPI.ScalePixelsDown(mi.rcMonitor.bottom);
System.ArgumentException: ''∞' is not a valid value for property 'To'.'

**Comment by krisdb2009** [comment]
Can you share the resolution and DPI setting for your monitor?

**Comment by Chakuza2006** [comment]
@krisdb2009 
CloseTopAnimation.To = DPI.ScalePixelsDown(mi.rcMonitor.bottom);
The DPI values are zero and also the bottom value is zero. You can use VisualTreeHelper.GetDpi(this); to get the current dpiscale to avoid this error.

**Comment by Chakuza2006** [comment]
using System.Windows.Media;

DPI = VisualTreeHelper.GetDpi(this); // fix this issue
CloseTopAnimation.To = DPI.ScalePixelsDown(mi.rcMonitor.bottom);

**Comment by krisdb2009** [comment]
Can you submit a pull request?

**Comment by JayHendu** [comment]
This app is so amazing and was working great for me.

I’m not sure what happened but I started getting this error.

Any suggestions on how to fix?


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: '∞' is not a valid value for property 'To'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValueInternal(DependencyProperty dp, Object value)
   at SuperLauncher.ModernLauncher.UpdateAnimations(Boolean Center)
   at SuperLauncher.ModernLauncher.OpenWindow(Boolean Center)
   at SuperLauncher.ModernLauncher.Icon_Click(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.WmMouseUp(MouseButtons button)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Private.CoreLib.dll
----------------------------------------
SuperLauncher
    Assembly Version: 2.0.5.0
    Win32 Version: 2.0.5.0
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/SuperLauncher.dll
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Runtime.dll
----------------------------------------
PresentationFramework
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7301
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7301
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/WindowsBase.dll
----------------------------------------
System.Xaml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7301
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Xaml.dll
----------------------------------------
PresentationCore
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7301
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/PresentationCore.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.ComponentModel.Primitives.dll
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Collections.dll
----------------------------------------
DirectWriteForwarder
    Assembly Version: 7.0.0.0
    Win32 Version: 7,0,323,7301 @Commit: 0a09c7d17212981cb4fd5907fa6a6214966a366d
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/DirectWriteForwarder.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Runtime.Extensions.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Runtime.InteropServices.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Diagnostics.Debug.dll
----------------------------------------
System.Runtime.CompilerServices.VisualC
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Runtime.CompilerServices.VisualC.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Threading.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Collections.NonGeneric.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7201
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7201
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Collections.Specialized.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Diagnostics.Process.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Private.Xml.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Memory.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Private.Uri.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Text.Encoding.Extensions.dll
----------------------------------------
System.IO.Packaging
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.IO.Packaging.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/Microsoft.Win32.Registry.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Threading.Thread.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Linq.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.ObjectModel.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Diagnostics.TraceSource.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.ComponentModel.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7301
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/UIAutomationTypes.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Threading.ThreadPool.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Windows.Extensions.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Collections.Concurrent.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Net.Requests.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Net.Primitives.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Drawing.Common.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Runtime.Loader.dll
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7301
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/PresentationFramework.Aero2.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7301
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/UIAutomationProvider.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Diagnostics.Tracing.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7301
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/PresentationFramework-SystemXml.dll
----------------------------------------
System.Windows.Controls.Ribbon
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7301
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Windows.Controls.Ribbon.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7301
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/WindowsFormsIntegration.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.7201
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Drawing.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Security.Claims.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Numerics.Vectors.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.323.6910
    CodeBase: file:///C:/Users/Public/below%20average/Super%20Launcher/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

**Comment by krisdb2009** [comment]
@JayHendu does it show up consistantly? What are the steps to produce the error?
Also, wondering what display model you have, resolution and DPI.

**Comment by JayHendu** [comment]
Phew, I sorted it out.  Basically the xml config file had entries that referenced invalid apps. Microsoft's OneDrive moved a bunch of my files from
C:\Users\xyz\Desktop\
to
C:\Users\xyz\OneDrive - alteryx.com\Desktop\
And so the orphaned references to the old location was throwing that error.  There certainly could have been a better error message.

**Comment by krisdb2009** [comment]
@JayHendu Interesting! I will try to re-produce and handle that error.
